<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-10-18T09:32:07+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Europe/London',
];
