<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-10-18T10:33:50+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      cache.full_page_lifetime_value
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'en_GB',
    'version_installed' => '8.2.1',
    'version_db_installed' => '20170802000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1508315561,
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ],
];
