<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-10-18T09:32:14+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'CDot Enterprises',
        ],
    ],
];
